# Generated by Django 5.2.12 on 2026-03-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='carrier_name',
            field=models.CharField(blank=True, default='', help_text='Name of the logistics carrier providing the service', max_length=255, null=True),
        ),
    ]
