# Generated by Django 4.2 on 2026-03-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_carrier_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-submitted_at'], 'verbose_name_plural': 'Bids'},
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled - Not Yet Started'), ('ACTIVE', 'Active - Bidding Open'), ('CLOSED', 'Closed - Bidding Ended'), ('FORCE_CLOSED', 'Force Closed - Hard Deadline Reached')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='auctionevent',
            name='event_type',
            field=models.CharField(choices=[('AUCTION_CREATED', 'Auction Created'), ('BID_RECEIVED', 'Bid Received'), ('BID_REVISED', 'Bid Revised'), ('RANK_CHANGED', 'Rank Changed'), ('L1_CHANGED', 'L1 (Lowest Bidder) Changed'), ('EXTENDED', 'Auction Extended'), ('CLOSED', 'Auction Closed'), ('FORCE_CLOSED', 'Force Closed')], help_text='Type of event', max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='carrier_name',
            field=models.CharField(blank=True, default='', help_text='Name of the logistics carrier providing the service', max_length=255),
        ),
    ]
