# Generated by Django 4.2 on 2026-03-29 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_options_alter_bid_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_status', models.CharField(choices=[('SCHEDULED', 'Scheduled - Not Yet Started'), ('ACTIVE', 'Active - Bidding Open'), ('CLOSED', 'Closed - Bidding Ended'), ('FORCE_CLOSED', 'Force Closed - Hard Deadline Reached')], max_length=20)),
                ('current_close_time', models.DateTimeField()),
                ('l1_bidder', models.CharField(blank=True, max_length=150)),
                ('l1_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bids', models.PositiveIntegerField()),
                ('unique_bidders', models.PositiveIntegerField()),
                ('total_extensions', models.PositiveIntegerField()),
                ('trigger_event', models.CharField(choices=[('BID_PLACED', 'Bid Placed'), ('EXTENSION', 'Auction Extended'), ('CLOSED', 'Auction Closed'), ('L1_CHANGE', 'L1 Changed')], max_length=50)),
                ('trigger_description', models.TextField()),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Auction Snapshots',
                'ordering': ['-snapshot_time'],
            },
        ),
        migrations.CreateModel(
            name='AuctionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bids_received', models.PositiveIntegerField()),
                ('unique_bidders', models.PositiveIntegerField()),
                ('avg_bids_per_bidder', models.FloatField()),
                ('initial_bid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_bid_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_reduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_reduction_percent', models.FloatField()),
                ('total_auction_duration', models.DurationField()),
                ('total_extension_time', models.DurationField()),
                ('first_bid_to_close_time', models.DurationField()),
                ('total_extensions', models.PositiveIntegerField()),
                ('bid_density', models.FloatField()),
                ('final_l1_bidder', models.CharField(blank=True, max_length=150)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Auction Statistics',
            },
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid_close_time',
            field=models.DateTimeField(help_text='Bid Close Date & Time (Asia/Kolkata timezone - IST, UTC+5:30)'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid_start_time',
            field=models.DateTimeField(help_text='Bid Start Date & Time (Asia/Kolkata timezone - IST, UTC+5:30)'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_close_time',
            field=models.DateTimeField(blank=True, help_text='Current effective close time (with extensions) - IST timezone', null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='forced_close_time',
            field=models.DateTimeField(help_text='Forced Bid Close Date & Time (must be > Bid Close Time) - IST timezone'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'bid_start_time'], name='auctions_au_status_2c4bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'current_close_time'], name='auctions_au_status_81067a_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status', 'forced_close_time'], name='auctions_au_status_4e8508_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['created_by', 'status'], name='auctions_au_created_646827_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['bid_close_time'], name='auctions_au_bid_clo_cbcd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['forced_close_time'], name='auctions_au_forced__f62324_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'bidder', '-submitted_at'], name='auctions_bi_auction_c81cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', 'submitted_at'], name='auctions_bi_auction_21266b_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-submitted_at'], name='auctions_bi_auction_0137c2_idx'),
        ),
        migrations.AddField(
            model_name='auctionstatistics',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='auctionsnapshot',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='auctions.auction'),
        ),
        migrations.AddIndex(
            model_name='auctionsnapshot',
            index=models.Index(fields=['auction', '-snapshot_time'], name='auctions_au_auction_76e78e_idx'),
        ),
    ]
